# Generated by Django 3.1.5 on 2021-01-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_confirm', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('main_page', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=24)),
                ('slug', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Artykuły', 'Artykuły'), ('Postacie', 'Postacie'), ('Miejsca', 'Miejsca'), ('Przedmioty', 'Przedmioty'), ('Stworzenia', 'Stworzenia'), ('Książki/Filmy', 'Książki/Filmy'), ('Inne', 'Inne')], max_length=15)),
                ('description', models.CharField(max_length=160)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('source', models.CharField(default='', max_length=160)),
                ('like', models.IntegerField(default=0)),
                ('unlike', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('confirm', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
            options={
                'ordering': ['-confirm', '-created_time'],
            },
        ),
    ]
