# Generated by Django 3.1.5 on 2021-01-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_confirm', models.BooleanField(default=False, verbose_name='zdjęcie zatwierdzone')),
                ('confirmed', models.BooleanField(default=False, verbose_name='zatwierdzony')),
                ('main_page', models.BooleanField(default=False, verbose_name='strona główna')),
                ('title', models.CharField(max_length=24, unique=True, verbose_name='tytuł')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('category', models.CharField(choices=[('Artykuły', 'Artykuły'), ('Postacie', 'Postacie'), ('Miejsca', 'Miejsca'), ('Przedmioty', 'Przedmioty'), ('Stworzenia', 'Stworzenia'), ('Książki/Filmy', 'Książki/Filmy'), ('Inne', 'Inne')], max_length=15, verbose_name='kategoria')),
                ('description', models.CharField(max_length=160, verbose_name='opis')),
                ('author', models.CharField(max_length=24, verbose_name='autor')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now=True, verbose_name='utworzono')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='zdjęcie')),
                ('source', models.CharField(blank=True, default='', max_length=160, verbose_name='źródło')),
                ('like', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0, verbose_name='wejścia')),
            ],
            options={
                'verbose_name': 'artykuł',
                'verbose_name_plural': 'artykuły',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='DailySimpleHit',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='data')),
                ('home_hits', models.IntegerField(default=0, verbose_name='strona główna')),
                ('category_hits', models.IntegerField(default=0, verbose_name='kategorie')),
                ('article_hits', models.IntegerField(default=0, verbose_name='artykuły')),
            ],
            options={
                'verbose_name': 'dzienne wejście',
                'verbose_name_plural': 'dzienne wejścia',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now=True, verbose_name='utworzono')),
                ('text', models.TextField(verbose_name='tekst')),
                ('confirm', models.BooleanField(default=False, verbose_name='zatwierdzona')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article', verbose_name='artykuł')),
            ],
            options={
                'verbose_name': 'wersja',
                'verbose_name_plural': 'wersje',
                'ordering': ['-confirm', '-created_time'],
            },
        ),
    ]
